### ISSUE TITLE
Different output prediction with CMSIS-NN as backend

### ISSUE THREAD

**Issue by angelocatalani** [majianjia/nnom#115]
Hi,
thanks for your great work!.

Do you have any ideas on why the prediction is always wrong when the `NNOM_USING_CMSIS_NN` is defined ?.

Without that optimization, the predictions are correct:
While in that case I always get the output predictions (4 classes with Softmax) always the same value: `32`.
 
 My model is a ResNet with 1D CNN and 1D max pool.
 This is how I used the API: `generate_model(model, x_test, name='quant_model.h', format='hwc')`.

**Comment by majianjia** [comment]
Hi @angelocatalani 
Could you explain more about the issue?
Is “Without that optimization” means the compiler's optimization option?
Thanks

**Comment by angelocatalani** [comment]
"Without that optimization" means the macro `NOM_USING_CMSIS_NN`  inside `port.h` is not defined:

```c
/* Backend selection */
//#define NNOM_USING_CMSIS_NN       // uncomment if use CMSIS-NN for optimation 
```

**Comment by majianjia** [comment]
which CMSIS version are you using? I am not sure if there is some changes since my last check. 
The ones I used were CMSIS 5.6.0 and 5.7.0

**Comment by angelocatalani** [comment]
thank you, I was using the `5.7.0` version. Downgrading to the `5.6.0` version seems to have solved the issue

**Comment by majianjia** [comment]
Thanks for testing, I will try to find the issue related to the cmsis 5.7.0
