### ISSUE TITLE
Q15 Support

### ISSUE THREAD

**Issue by HadeelMabrouk** [majianjia/nnom#138]
Does the current implementation support using Q15 format for quantization instead of Q7? 
If so, how can it be applied? I couldn't find relevant information in the documentation.
TIA.

**Comment by majianjia** [comment]
The current implementation only supports Q7. With a few exceptions, RNN type layers use Q15 internally and state. 
I am working on Q15 and the new CMSIS-NN interface. The backend is almost ready but still much works to do. 
Not sure how long does it take.

**Comment by HadeelMabrouk** [comment]
Noted. Thanks!
