### ISSUE TITLE
About used time?

### ISSUE THREAD

**Issue by panhu** [majianjia/nnom#192]
您好：
我想要知道模型推理消耗的时间，但是使用nnom_ms_get或者nnom_us_get()，得到的最终结果好像都是0. 不知道是否还需要进行别的设置或者参数修改。

**Comment by majianjia** [comment]
你需要移植这两个函数
https://github.com/majianjia/nnom/blob/1be7dfdd3fd677a64b0c733db6d400d7346a6eca/port/nnom_port.h#L36

**Comment by jonnor** [comment]
I believe this has been answered, and should be closed. CC @majianjia
