### ISSUE TITLE
Quantizing Input for Generate_Test_Bin()?

### ISSUE THREAD

**Issue by Kelvin-Chan** [majianjia/nnom#47]
Hello,

For the `generate_test_bin()` utility function, the [documentation](https://majianjia.github.io/nnom/api_nnom_utils/#generate_test_bin) says to provide a quantized input `x` into the utility function, but when I look at the script, it seems to already quantize the input.

https://github.com/majianjia/nnom/blob/3f245721b14221a5e3c3a8e8760666bed94eafbf/scripts/nnom_utils.py#L67-L80

My current `x_test` are already floating values between (0~1). Do I still need to multiply by `127` (2*7 - 1) to first convert to Q7 before using `generate_test_bin()`, or should I leave it as is?

**Comment by majianjia** [comment]
Hi @Kelvin-Chan,
I think you can leave it as it is. It is probably the mistake in the documentation.
