### ISSUE TITLE
1D vector problem

### ISSUE THREAD

**Issue by giusseppeone** [majianjia/nnom#88]
Hi Majianjia ,
I tested NNOM and ran into such a problem. I created a primitive model for the implementation of the XOR problem. 
![1_Model](https://user-images.githubusercontent.com/71380012/93322992-43dfdb80-f814-11ea-8f7c-6f42e68a26eb.jpg)
After train and generate model the values appear to be OK
![2_AfterTrain1](https://user-images.githubusercontent.com/71380012/93323107-78539780-f814-11ea-9298-c11094dd1c49.jpg)
![3_AfterTrain2](https://user-images.githubusercontent.com/71380012/93323114-7a1d5b00-f814-11ea-9013-9238130b3144.jpg)
After test on STM32G431 I found this problem (input is one dim vector as created in jupyter => input shape(2,) )
![4_elipseERR](https://user-images.githubusercontent.com/71380012/93323295-b650bb80-f814-11ea-9f23-37dca182a48d.jpg)
and output from console is
![5_consoleOutERR](https://user-images.githubusercontent.com/71380012/93323347-c7013180-f814-11ea-8b5d-186f855b5268.jpg)
I tried to modify the code to test the functionality
![6_ChangeCodeForTest](https://user-images.githubusercontent.com/71380012/93323908-7ccc8000-f815-11ea-805f-8d0b06dd64a9.jpg)
after run the code output is OK ane value is ok too. 
![7_AfterCodeChangeConsoleOK](https://user-images.githubusercontent.com/71380012/93324022-a4234d00-f815-11ea-8d85-0f5efad41734.jpg)
My question is , can work NNOM with input shape=(2,) ?
Thank you , nnom is excellent job :)

**Comment by majianjia** [comment]
The current Input layer only can take 3d shape data. For 2D data, the Input will still expend the shape to 3d.
But there is no implementation to expend 1D data to 3D, which is also not a good solution for the future. So I didnt implement this. 
This is an very old idea which NNoM was primary only focus on 2D image (3D data)

I recently look back to this issue and are planning to change it.
In the future version I will make Input to support native 1D and 2D data. But it requires some works to do.

The current solution for 1D data is to at least expend the input shape in keras to 2d then use flatten() in keras to convert it to 1D. 
Just use input_shape=(1, x) then use a flatten following by it.

**Comment by giusseppeone** [comment]
Thanks for answer , 
I tested with input_shape =(1,x) it works well , 
many thanks
