### ISSUE TITLE
implicit declaration of function 'avgpool_s'

### ISSUE THREAD

**Issue by sifourquier** [majianjia/nnom#93]
I think  #include "layers/nnom_avgpool.h" is missing in nnom/inc/nnom_layers.h
If i add it it is ok

**Comment by majianjia** [comment]
Thanks, you are right!
If you dont might, you can send a pull request and I will merge it to the master. Otherwise, I will correct it in a latter commit. 
Jianjia

**Comment by jonnor** [comment]
This issue has been fixed and can be closed. CC @majianjia
